//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CanBuyWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product_Images
    {
        public int ID { get; set; }
        public int Product_Id { get; set; }
        public string Image_Path { get; set; }
        public byte[] Image_Byte { get; set; }
        public bool IsPrimary { get; set; }
        public int Sort { get; set; }
    
        public virtual Products Products { get; set; }
    }
}
