//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CanBuyWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rotation
    {
        public int ID { get; set; }
        public System.DateTime Created { get; set; }
        public string IP { get; set; }
        public Nullable<int> ProductId { get; set; }
        public Nullable<int> UserId { get; set; }
    }
}
