//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CanBuyWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class temp_image
    {
        public int ID { get; set; }
        public string image_Path { get; set; }
        public byte[] image_Byte { get; set; }
        public System.DateTime created { get; set; }
        public bool deleted { get; set; }
        public string userId { get; set; }
    }
}
