//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CanBuyWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class temp_image
    {
        public int ID { get; set; }
        public string image_Path { get; set; }
        public byte[] image_Byte { get; set; }
        public System.DateTime created { get; set; }
        public bool deleted { get; set; }
        public string userId { get; set; }
    }
}
